/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokercash.vista.mesa;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author CyberLink
 */
public class VistaDialogoMesa extends javax.swing.JDialog {

    /**
     * Creates new form VistaDialogo
     */
    public VistaDialogoMesa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelOrganizacion = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cbxClub = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListClub = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        cbxOrg = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListOrg = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        rbPorc = new javax.swing.JRadioButton();
        rbEfect = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbCgastos = new javax.swing.JRadioButton();
        rbSgastos = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtClubPor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClubEf = new javax.swing.JTextField();
        btnAgregarClub = new javax.swing.JButton();
        btnRemoverClub = new javax.swing.JButton();
        btnAgregarOrg = new javax.swing.JButton();
        btnRemoverOrg = new javax.swing.JButton();
        bgPago = new javax.swing.ButtonGroup();
        bgGastos = new javax.swing.ButtonGroup();
        bgDeler = new javax.swing.ButtonGroup();
        PanelTrabajadores = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnSeleccionart = new javax.swing.JButton();
        btnRemovert = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaTrabajadores = new javax.swing.JTable();
        dlgEmpleados = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        btnCancelarte = new javax.swing.JButton();
        btnAceptarte = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarte = new javax.swing.JButton();
        PanelPagos = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbPropservi = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        cbEfectserv = new javax.swing.JCheckBox();
        txtPropServi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEfectServi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        cbCasiDeler = new javax.swing.JCheckBox();
        txtCasiDeler = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rbGastoDeler = new javax.swing.JRadioButton();
        rbCgastosDeler = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtValorAdm = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtEfectDeler = new javax.swing.JTextField();
        cbPropDeler = new javax.swing.JCheckBox();
        cbEfectDeler = new javax.swing.JCheckBox();
        txtPropDeler = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtInformacion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Organización");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("1. Seleccionar dueño/s del club");

        jScrollPane1.setViewportView(ListClub);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("3. Seleccionar organizador/es");

        jScrollPane2.setViewportView(ListOrg);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("2. Seleccionar pago al club");

        bgPago.add(rbPorc);
        rbPorc.setSelected(true);
        rbPorc.setText("Porcentaje");

        bgPago.add(rbEfect);
        rbEfect.setText("Efectivo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("4. Seleccionar pago de gastos");

        bgGastos.add(rbCgastos);
        rbCgastos.setSelected(true);
        rbCgastos.setText("Con gastos");

        bgGastos.add(rbSgastos);
        rbSgastos.setText("Sin gastos");

        jLabel6.setText("$");

        txtClubPor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtClubPor.setText("100");

        jLabel7.setText("%");

        txtClubEf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtClubEf.setText("0");
        txtClubEf.setEnabled(false);

        btnAgregarClub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/action_check.png"))); // NOI18N
        btnAgregarClub.setBorder(null);
        btnAgregarClub.setContentAreaFilled(false);
        btnAgregarClub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnRemoverClub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/action_delete.png"))); // NOI18N
        btnRemoverClub.setBorder(null);
        btnRemoverClub.setContentAreaFilled(false);
        btnRemoverClub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAgregarOrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/action_check.png"))); // NOI18N
        btnAgregarOrg.setBorder(null);
        btnAgregarOrg.setContentAreaFilled(false);
        btnAgregarOrg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnRemoverOrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/action_delete.png"))); // NOI18N
        btnRemoverOrg.setBorder(null);
        btnRemoverOrg.setContentAreaFilled(false);
        btnRemoverOrg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbEfect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbPorc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(txtClubPor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtClubEf, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbxClub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarClub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoverClub)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbCgastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(cbxOrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAgregarOrg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemoverOrg)))
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addComponent(rbSgastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemoverClub, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAgregarClub, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(cbxClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverOrg)
                            .addComponent(btnAgregarOrg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPorc)
                            .addComponent(txtClubPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbEfect)
                            .addComponent(jLabel6)
                            .addComponent(txtClubEf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCgastos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbSgastos)))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelOrganizacionLayout = new javax.swing.GroupLayout(PanelOrganizacion);
        PanelOrganizacion.setLayout(PanelOrganizacionLayout);
        PanelOrganizacionLayout.setHorizontalGroup(
            PanelOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOrganizacionLayout.setVerticalGroup(
            PanelOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel9.setText("Seleccionar trabajador");

        btnSeleccionart.setText("Seleccionar");

        btnRemovert.setText("Remover");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Trabajadores");

        TablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaTrabajadores.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TablaTrabajadores);

        javax.swing.GroupLayout PanelTrabajadoresLayout = new javax.swing.GroupLayout(PanelTrabajadores);
        PanelTrabajadores.setLayout(PanelTrabajadoresLayout);
        PanelTrabajadoresLayout.setHorizontalGroup(
            PanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTrabajadoresLayout.createSequentialGroup()
                        .addGroup(PanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(PanelTrabajadoresLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 336, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))
                    .addGroup(PanelTrabajadoresLayout.createSequentialGroup()
                        .addGroup(PanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTrabajadoresLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(btnSeleccionart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemovert))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelTrabajadoresLayout.setVerticalGroup(
            PanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnSeleccionart)
                    .addComponent(btnRemovert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );

        dlgEmpleados.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dlgEmpleados.setTitle("Seleccionar Empleado");
        dlgEmpleados.setResizable(false);

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaEmpleados.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(TablaEmpleados);

        btnCancelarte.setText("Cancelar");

        btnAceptarte.setText("Aceptar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Lista de Empleados");

        btnAgregarte.setText("Agregar");

        javax.swing.GroupLayout dlgEmpleadosLayout = new javax.swing.GroupLayout(dlgEmpleados.getContentPane());
        dlgEmpleados.getContentPane().setLayout(dlgEmpleadosLayout);
        dlgEmpleadosLayout.setHorizontalGroup(
            dlgEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgEmpleadosLayout.createSequentialGroup()
                        .addComponent(btnAceptarte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarte))
                    .addGroup(dlgEmpleadosLayout.createSequentialGroup()
                        .addGroup(dlgEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(btnAgregarte))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dlgEmpleadosLayout.setVerticalGroup(
            dlgEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarte)
                    .addComponent(btnAceptarte))
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Servicio");

        cbPropservi.setText("Propinas");
        cbPropservi.setEnabled(false);

        cbEfectserv.setText("Efectivo");
        cbEfectserv.setEnabled(false);

        txtPropServi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPropServi.setText("0");
        txtPropServi.setEnabled(false);

        jLabel13.setText("%");

        jLabel14.setText("$");

        txtEfectServi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEfectServi.setText("0");
        txtEfectServi.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Administrador");

        jLabel20.setText("%");

        cbCasiDeler.setText("Casilla");

        txtCasiDeler.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCasiDeler.setText("0");
        txtCasiDeler.setEnabled(false);

        jLabel21.setText("%");

        bgDeler.add(rbGastoDeler);
        rbGastoDeler.setSelected(true);
        rbGastoDeler.setText("Sin gastos");

        bgDeler.add(rbCgastosDeler);
        rbCgastosDeler.setText("Con gastos");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Confiigurar pago de trabajadores");

        jLabel16.setText("Valor:");

        txtValorAdm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorAdm.setText("0");
        txtValorAdm.setEnabled(false);

        jLabel17.setText("$");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Deler");

        jLabel19.setText("$");

        txtEfectDeler.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEfectDeler.setText("0");
        txtEfectDeler.setEnabled(false);

        cbPropDeler.setText("Propinas");

        cbEfectDeler.setText("Efectivo");

        txtPropDeler.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPropDeler.setText("0");
        txtPropDeler.setEnabled(false);

        javax.swing.GroupLayout PanelPagosLayout = new javax.swing.GroupLayout(PanelPagos);
        PanelPagos.setLayout(PanelPagosLayout);
        PanelPagosLayout.setHorizontalGroup(
            PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator5)
                    .addGroup(PanelPagosLayout.createSequentialGroup()
                        .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPagosLayout.createSequentialGroup()
                                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12)
                                    .addComponent(cbPropservi, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(cbEfectserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelPagosLayout.createSequentialGroup()
                                        .addComponent(txtPropServi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(PanelPagosLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEfectServi))))
                            .addComponent(jLabel15)
                            .addGroup(PanelPagosLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18)
                            .addGroup(PanelPagosLayout.createSequentialGroup()
                                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbCasiDeler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbPropDeler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbEfectDeler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPagosLayout.createSequentialGroup()
                                        .addComponent(txtCasiDeler, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21))
                                    .addGroup(PanelPagosLayout.createSequentialGroup()
                                        .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPagosLayout.createSequentialGroup()
                                                .addComponent(txtPropDeler, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20))
                                            .addGroup(PanelPagosLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEfectDeler, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(33, 33, 33)
                                        .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rbCgastosDeler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rbGastoDeler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelPagosLayout.setVerticalGroup(
            PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPropservi)
                    .addComponent(txtPropServi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEfectserv)
                    .addComponent(jLabel14)
                    .addComponent(txtEfectServi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(txtValorAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPagosLayout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPropDeler)
                            .addComponent(txtPropDeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(rbCgastosDeler))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEfectDeler)
                            .addComponent(jLabel19)
                            .addComponent(txtEfectDeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(rbGastoDeler, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCasiDeler)
                    .addComponent(txtCasiDeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Steps");

        txtInformacion.setColumns(20);
        txtInformacion.setRows(5);
        txtInformacion.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtInformacion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        btnCancelar.setText("Cancelar");

        btnFinalizar.setText("Finalizar");

        btnSiguiente.setText("Siguiente");

        btnAtras.setText("Atras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnFinalizar)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAtras))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAgregarClub() {
        return btnAgregarClub;
    }

    public void setBtnAgregarClub(JButton btnAgregarClub) {
        this.btnAgregarClub = btnAgregarClub;
    }

    public JButton getBtnAgregarOrg() {
        return btnAgregarOrg;
    }

    public void setBtnAgregarOrg(JButton btnAgregarOrg) {
        this.btnAgregarOrg = btnAgregarOrg;
    }

    public JButton getBtnRemoverClub() {
        return btnRemoverClub;
    }

    public void setBtnRemoverClub(JButton btnRemoverClub) {
        this.btnRemoverClub = btnRemoverClub;
    }

    public JButton getBtnRemoverOrg() {
        return btnRemoverOrg;
    }

    public void setBtnRemoverOrg(JButton btnRemoverOrg) {
        this.btnRemoverOrg = btnRemoverOrg;
    }

    
    
    public JPanel getContent() {
        return content;
    }

    public void setContent(JPanel content) {
        this.content = content;
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JList<String> getListClub() {
        return ListClub;
    }

    public void setListClub(JList<String> ListClub) {
        this.ListClub = ListClub;
    }

    public JList<String> getListOrg() {
        return ListOrg;
    }

    public void setListOrg(JList<String> ListOrg) {
        this.ListOrg = ListOrg;
    }

    public JPanel getPanelOrganizacion() {
        return PanelOrganizacion;
    }

    public void setPanelOrganizacion(JPanel PanelOrganizacion) {
        this.PanelOrganizacion = PanelOrganizacion;
    }

    public ButtonGroup getBgDeler() {
        return bgDeler;
    }

    public void setBgDeler(ButtonGroup bgDeler) {
        this.bgDeler = bgDeler;
    }

    public ButtonGroup getBgGastos() {
        return bgGastos;
    }

    public void setBgGastos(ButtonGroup bgGastos) {
        this.bgGastos = bgGastos;
    }

    public ButtonGroup getBgPago() {
        return bgPago;
    }

    public void setBgPago(ButtonGroup bgPago) {
        this.bgPago = bgPago;
    }

    public JComboBox<String> getCbxClub() {
        return cbxClub;
    }

    public void setCbxClub(JComboBox<String> cbxClub) {
        this.cbxClub = cbxClub;
    }

    public JComboBox<String> getCbxOrg() {
        return cbxOrg;
    }

    public void setCbxOrg(JComboBox<String> cbxOrg) {
        this.cbxOrg = cbxOrg;
    }

    public JRadioButton getRbCgastos() {
        return rbCgastos;
    }

    public void setRbCgastos(JRadioButton rbCgastos) {
        this.rbCgastos = rbCgastos;
    }

    public JRadioButton getRbEfect() {
        return rbEfect;
    }

    public void setRbEfect(JRadioButton rbEfect) {
        this.rbEfect = rbEfect;
    }

    public JRadioButton getRbPorc() {
        return rbPorc;
    }

    public void setRbPorc(JRadioButton rbPorc) {
        this.rbPorc = rbPorc;
    }

    public JRadioButton getRbSgastos() {
        return rbSgastos;
    }

    public void setRbSgastos(JRadioButton rbSgastos) {
        this.rbSgastos = rbSgastos;
    }

    public JTextField getTxtClubEf() {
        return txtClubEf;
    }

    public void setTxtClubEf(JTextField txtClubEf) {
        this.txtClubEf = txtClubEf;
    }

    public JTextField getTxtClubPor() {
        return txtClubPor;
    }

    public void setTxtClubPor(JTextField txtClubPor) {
        this.txtClubPor = txtClubPor;
    }

    public JPanel getPanelPagos() {
        return PanelPagos;
    }

    public void setPanelPagos(JPanel PanelPagos) {
        this.PanelPagos = PanelPagos;
    }

    public JPanel getPanelTrabajadores() {
        return PanelTrabajadores;
    }

    public void setPanelTrabajadores(JPanel PanelTrabajadores) {
        this.PanelTrabajadores = PanelTrabajadores;
    }

    public JTable getTablaEmpleados() {
        return TablaEmpleados;
    }

    public void setTablaEmpleados(JTable TablaEmpleados) {
        this.TablaEmpleados = TablaEmpleados;
    }

    public JTable getTablaTrabajadores() {
        return TablaTrabajadores;
    }

    public void setTablaTrabajadores(JTable TablaTrabajadores) {
        this.TablaTrabajadores = TablaTrabajadores;
    }

    public JButton getBtnAceptarte() {
        return btnAceptarte;
    }

    public void setBtnAceptarte(JButton btnAceptarte) {
        this.btnAceptarte = btnAceptarte;
    }

    public JButton getBtnAgregarte() {
        return btnAgregarte;
    }

    public void setBtnAgregarte(JButton btnAgregarte) {
        this.btnAgregarte = btnAgregarte;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnCancelarte() {
        return btnCancelarte;
    }

    public void setBtnCancelarte(JButton btnCancelarte) {
        this.btnCancelarte = btnCancelarte;
    }

    public JButton getBtnFinalizar() {
        return btnFinalizar;
    }

    public void setBtnFinalizar(JButton btnFinalizar) {
        this.btnFinalizar = btnFinalizar;
    }

    public JButton getBtnRemovert() {
        return btnRemovert;
    }

    public void setBtnRemovert(JButton btnRemovert) {
        this.btnRemovert = btnRemovert;
    }

    public JButton getBtnSeleccionart() {
        return btnSeleccionart;
    }

    public void setBtnSeleccionart(JButton btnSeleccionart) {
        this.btnSeleccionart = btnSeleccionart;
    }

    public JCheckBox getCbCasiDeler() {
        return cbCasiDeler;
    }

    public void setCbCasiDeler(JCheckBox cbCasiDeler) {
        this.cbCasiDeler = cbCasiDeler;
    }

    public JCheckBox getCbEfectDeler() {
        return cbEfectDeler;
    }

    public void setCbEfectDeler(JCheckBox cbEfectDeler) {
        this.cbEfectDeler = cbEfectDeler;
    }

    public JCheckBox getCbEfectserv() {
        return cbEfectserv;
    }

    public void setCbEfectserv(JCheckBox cbEfectserv) {
        this.cbEfectserv = cbEfectserv;
    }

    public JCheckBox getCbPropDeler() {
        return cbPropDeler;
    }

    public void setCbPropDeler(JCheckBox cbPropDeler) {
        this.cbPropDeler = cbPropDeler;
    }

    public JCheckBox getCbPropservi() {
        return cbPropservi;
    }

    public void setCbPropservi(JCheckBox cbPropservi) {
        this.cbPropservi = cbPropservi;
    }

    public JDialog getDlgEmpleados() {
        return dlgEmpleados;
    }

    public void setDlgEmpleados(JDialog dlgEmpleados) {
        this.dlgEmpleados = dlgEmpleados;
    }

    public JRadioButton getRbCgastosDeler() {
        return rbCgastosDeler;
    }

    public void setRbCgastosDeler(JRadioButton rbCgastosDeler) {
        this.rbCgastosDeler = rbCgastosDeler;
    }

    public JRadioButton getRbGastoDeler() {
        return rbGastoDeler;
    }

    public void setRbGastoDeler(JRadioButton rbGastoDeler) {
        this.rbGastoDeler = rbGastoDeler;
    }

    public JTextField getTxtCasiDeler() {
        return txtCasiDeler;
    }

    public void setTxtCasiDeler(JTextField txtCasiDeler) {
        this.txtCasiDeler = txtCasiDeler;
    }

    public JTextField getTxtEfectDeler() {
        return txtEfectDeler;
    }

    public void setTxtEfectDeler(JTextField txtEfectDeler) {
        this.txtEfectDeler = txtEfectDeler;
    }

    public JTextField getTxtEfectServi() {
        return txtEfectServi;
    }

    public void setTxtEfectServi(JTextField txtEfectServi) {
        this.txtEfectServi = txtEfectServi;
    }

    public JTextField getTxtPropDeler() {
        return txtPropDeler;
    }

    public void setTxtPropDeler(JTextField txtPropDeler) {
        this.txtPropDeler = txtPropDeler;
    }

    public JTextField getTxtPropServi() {
        return txtPropServi;
    }

    public void setTxtPropServi(JTextField txtPropServi) {
        this.txtPropServi = txtPropServi;
    }

    public JTextField getTxtValorAdm() {
        return txtValorAdm;
    }

    public void setTxtValorAdm(JTextField txtValorAdm) {
        this.txtValorAdm = txtValorAdm;
    }

    public JTextArea getTxtInformacion() {
        return txtInformacion;
    }

    public void setTxtInformacion(JTextArea txtInformacion) {
        this.txtInformacion = txtInformacion;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListClub;
    private javax.swing.JList<String> ListOrg;
    private javax.swing.JPanel PanelOrganizacion;
    private javax.swing.JPanel PanelPagos;
    private javax.swing.JPanel PanelTrabajadores;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JTable TablaTrabajadores;
    private javax.swing.ButtonGroup bgDeler;
    private javax.swing.ButtonGroup bgGastos;
    private javax.swing.ButtonGroup bgPago;
    private javax.swing.JButton btnAceptarte;
    private javax.swing.JButton btnAgregarClub;
    private javax.swing.JButton btnAgregarOrg;
    private javax.swing.JButton btnAgregarte;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarte;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemoverClub;
    private javax.swing.JButton btnRemoverOrg;
    private javax.swing.JButton btnRemovert;
    private javax.swing.JButton btnSeleccionart;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBox cbCasiDeler;
    private javax.swing.JCheckBox cbEfectDeler;
    private javax.swing.JCheckBox cbEfectserv;
    private javax.swing.JCheckBox cbPropDeler;
    private javax.swing.JCheckBox cbPropservi;
    private javax.swing.JComboBox<String> cbxClub;
    private javax.swing.JComboBox<String> cbxOrg;
    private javax.swing.JPanel content;
    private javax.swing.JDialog dlgEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton rbCgastos;
    private javax.swing.JRadioButton rbCgastosDeler;
    private javax.swing.JRadioButton rbEfect;
    private javax.swing.JRadioButton rbGastoDeler;
    private javax.swing.JRadioButton rbPorc;
    private javax.swing.JRadioButton rbSgastos;
    private javax.swing.JTextField txtCasiDeler;
    private javax.swing.JTextField txtClubEf;
    private javax.swing.JTextField txtClubPor;
    private javax.swing.JTextField txtEfectDeler;
    private javax.swing.JTextField txtEfectServi;
    private javax.swing.JTextArea txtInformacion;
    private javax.swing.JTextField txtPropDeler;
    private javax.swing.JTextField txtPropServi;
    private javax.swing.JTextField txtValorAdm;
    // End of variables declaration//GEN-END:variables
}
