/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokercash.vista.mesa;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author CyberLink
 */
public class VistaMesa extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMesa
     */
    public VistaMesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPago = new javax.swing.ButtonGroup();
        bgGastos = new javax.swing.ButtonGroup();
        dlgOrganizacion = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cbxClub = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListClub = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        cbxOrg = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListOrg = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        rbPorc = new javax.swing.JRadioButton();
        rbEfect = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbCgastos = new javax.swing.JRadioButton();
        rbSgastos = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtClubPor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClubEf = new javax.swing.JTextField();
        dlgTrabajadores = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaTrabajadores = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnSeleccionart = new javax.swing.JButton();
        btnRemovert = new javax.swing.JButton();
        btnCancelart = new javax.swing.JButton();
        btnSiguientet = new javax.swing.JButton();
        dlgeEmpleados = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        btnCancelarte = new javax.swing.JButton();
        btnAceptarte = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarte = new javax.swing.JButton();
        dlgPagos = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbPropservi = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        cbEfectserv = new javax.swing.JCheckBox();
        txtPropServi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEfectServi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtValorAdm = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtEfectDeler = new javax.swing.JTextField();
        cbPropDeler = new javax.swing.JCheckBox();
        cbEfectDeler = new javax.swing.JCheckBox();
        txtPropDeler = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbCasiDeler = new javax.swing.JCheckBox();
        txtCasiDeler = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rbGastoDeler = new javax.swing.JRadioButton();
        rbCgastosDeler = new javax.swing.JRadioButton();
        btnCancelarTr = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        bgDeler = new javax.swing.ButtonGroup();

        dlgOrganizacion.setResizable(false);

        btnSiguiente.setText("Siguiente");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSiguiente))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Organización");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("1. Seleccionar dueño/s del club");

        jScrollPane1.setViewportView(ListClub);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("3. Seleccionar organizador/es");

        jScrollPane2.setViewportView(ListOrg);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("2. Seleccionar pago al club");

        bgPago.add(rbPorc);
        rbPorc.setSelected(true);
        rbPorc.setText("Porcentaje");

        bgPago.add(rbEfect);
        rbEfect.setText("Efectivo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("4. Seleccionar pago de gastos");

        bgGastos.add(rbCgastos);
        rbCgastos.setSelected(true);
        rbCgastos.setText("Con gastos");

        bgGastos.add(rbSgastos);
        rbSgastos.setText("Sin gastos");

        jLabel6.setText("$");

        txtClubPor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtClubPor.setText("100");

        jLabel7.setText("%");

        txtClubEf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtClubEf.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxClub, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbEfect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbPorc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtClubPor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtClubEf, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbCgastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(cbxOrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(rbSgastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPorc)
                            .addComponent(txtClubPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbEfect)
                            .addComponent(jLabel6)
                            .addComponent(txtClubEf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCgastos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbSgastos)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgOrganizacionLayout = new javax.swing.GroupLayout(dlgOrganizacion.getContentPane());
        dlgOrganizacion.getContentPane().setLayout(dlgOrganizacionLayout);
        dlgOrganizacionLayout.setHorizontalGroup(
            dlgOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgOrganizacionLayout.setVerticalGroup(
            dlgOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgOrganizacionLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dlgTrabajadores.setResizable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Trabajadores");

        TablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaTrabajadores.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TablaTrabajadores);

        jLabel9.setText("Seleccionar trabajador");

        btnSeleccionart.setText("Seleccionar");

        btnRemovert.setText("Remover");

        btnCancelart.setText("Cancelar");

        btnSiguientet.setText("Siguiente");

        javax.swing.GroupLayout dlgTrabajadoresLayout = new javax.swing.GroupLayout(dlgTrabajadores.getContentPane());
        dlgTrabajadores.getContentPane().setLayout(dlgTrabajadoresLayout);
        dlgTrabajadoresLayout.setHorizontalGroup(
            dlgTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(dlgTrabajadoresLayout.createSequentialGroup()
                        .addGroup(dlgTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(dlgTrabajadoresLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(btnSeleccionart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemovert))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgTrabajadoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSiguientet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelart)))
                .addContainerGap())
        );
        dlgTrabajadoresLayout.setVerticalGroup(
            dlgTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnSeleccionart)
                    .addComponent(btnRemovert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelart)
                    .addComponent(btnSiguientet))
                .addContainerGap())
        );

        dlgeEmpleados.setResizable(false);

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaEmpleados.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(TablaEmpleados);

        btnCancelarte.setText("Cancelar");

        btnAceptarte.setText("Aceptar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Lista de Empleados");

        btnAgregarte.setText("Agregar");

        javax.swing.GroupLayout dlgeEmpleadosLayout = new javax.swing.GroupLayout(dlgeEmpleados.getContentPane());
        dlgeEmpleados.getContentPane().setLayout(dlgeEmpleadosLayout);
        dlgeEmpleadosLayout.setHorizontalGroup(
            dlgeEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgeEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgeEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgeEmpleadosLayout.createSequentialGroup()
                        .addComponent(btnAceptarte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarte))
                    .addGroup(dlgeEmpleadosLayout.createSequentialGroup()
                        .addGroup(dlgeEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(btnAgregarte))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dlgeEmpleadosLayout.setVerticalGroup(
            dlgeEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgeEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgeEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarte)
                    .addComponent(btnAceptarte))
                .addContainerGap())
        );

        dlgPagos.setResizable(false);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Confiigurar pago de trabajadores");

        jLabel12.setText("Servicio:");

        cbPropservi.setText("Propinas");

        cbEfectserv.setText("Efectivo");

        txtPropServi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPropServi.setText("100");

        jLabel13.setText("%");

        jLabel14.setText("$");

        txtEfectServi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEfectServi.setText("0");

        jLabel15.setText("Administrador");

        jLabel16.setText("Valor:");

        txtValorAdm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorAdm.setText("50");

        jLabel17.setText("$");

        jLabel18.setText("Deler");

        jLabel19.setText("$");

        txtEfectDeler.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEfectDeler.setText("0");

        cbPropDeler.setText("Propinas");

        cbEfectDeler.setText("Efectivo");

        txtPropDeler.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPropDeler.setText("100");

        jLabel20.setText("%");

        cbCasiDeler.setText("Casilla");

        txtCasiDeler.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCasiDeler.setText("15");

        jLabel21.setText("%");

        bgDeler.add(rbGastoDeler);
        rbGastoDeler.setSelected(true);
        rbGastoDeler.setText("Sin gastos");

        bgDeler.add(rbCgastosDeler);
        rbCgastosDeler.setText("Con gastos");

        btnCancelarTr.setText("Cancelar");

        btnFinalizar.setText("Finalizar");

        javax.swing.GroupLayout dlgPagosLayout = new javax.swing.GroupLayout(dlgPagos.getContentPane());
        dlgPagos.getContentPane().setLayout(dlgPagosLayout);
        dlgPagosLayout.setHorizontalGroup(
            dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator5)
                    .addGroup(dlgPagosLayout.createSequentialGroup()
                        .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgPagosLayout.createSequentialGroup()
                                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12)
                                    .addComponent(cbPropservi, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(cbEfectserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(dlgPagosLayout.createSequentialGroup()
                                        .addComponent(txtPropServi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(dlgPagosLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEfectServi))))
                            .addComponent(jLabel15)
                            .addGroup(dlgPagosLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18)
                            .addGroup(dlgPagosLayout.createSequentialGroup()
                                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbCasiDeler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbPropDeler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbEfectDeler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dlgPagosLayout.createSequentialGroup()
                                        .addComponent(txtCasiDeler, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21))
                                    .addGroup(dlgPagosLayout.createSequentialGroup()
                                        .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(dlgPagosLayout.createSequentialGroup()
                                                .addComponent(txtPropDeler, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20))
                                            .addGroup(dlgPagosLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEfectDeler, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(33, 33, 33)
                                        .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rbCgastosDeler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rbGastoDeler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgPagosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarTr)))
                .addContainerGap())
        );
        dlgPagosLayout.setVerticalGroup(
            dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPropservi)
                    .addComponent(txtPropServi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEfectserv)
                    .addComponent(jLabel14)
                    .addComponent(txtEfectServi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(txtValorAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgPagosLayout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPropDeler)
                            .addComponent(txtPropDeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(rbCgastosDeler))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEfectDeler)
                            .addComponent(jLabel19)
                            .addComponent(txtEfectDeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(rbGastoDeler, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCasiDeler)
                    .addComponent(txtCasiDeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(dlgPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarTr)
                    .addComponent(btnFinalizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JList<String> getListClub() {
        return ListClub;
    }

    public void setListClub(JList<String> ListClub) {
        this.ListClub = ListClub;
    }

    public JList<String> getListOrg() {
        return ListOrg;
    }

    public void setListOrg(JList<String> ListOrg) {
        this.ListOrg = ListOrg;
    }

    public JTable getTablaEmpleados() {
        return TablaEmpleados;
    }

    public void setTablaEmpleados(JTable TablaEmpleados) {
        this.TablaEmpleados = TablaEmpleados;
    }

    public JTable getTablaTrabajadores() {
        return TablaTrabajadores;
    }

    public void setTablaTrabajadores(JTable TablaTrabajadores) {
        this.TablaTrabajadores = TablaTrabajadores;
    }

    public ButtonGroup getBgDeler() {
        return bgDeler;
    }

    public void setBgDeler(ButtonGroup bgDeler) {
        this.bgDeler = bgDeler;
    }

    public ButtonGroup getBgGastos() {
        return bgGastos;
    }

    public void setBgGastos(ButtonGroup bgGastos) {
        this.bgGastos = bgGastos;
    }

    public ButtonGroup getBgPago() {
        return bgPago;
    }

    public void setBgPago(ButtonGroup bgPago) {
        this.bgPago = bgPago;
    }

    public JButton getBtnAceptarte() {
        return btnAceptarte;
    }

    public void setBtnAceptarte(JButton btnAceptarte) {
        this.btnAceptarte = btnAceptarte;
    }

    public JButton getBtnAgregarte() {
        return btnAgregarte;
    }

    public void setBtnAgregarte(JButton btnAgregarte) {
        this.btnAgregarte = btnAgregarte;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnCancelarTr() {
        return btnCancelarTr;
    }

    public void setBtnCancelarTr(JButton btnCancelarTr) {
        this.btnCancelarTr = btnCancelarTr;
    }

    public JButton getBtnCancelart() {
        return btnCancelart;
    }

    public void setBtnCancelart(JButton btnCancelart) {
        this.btnCancelart = btnCancelart;
    }

    public JButton getBtnCancelarte() {
        return btnCancelarte;
    }

    public void setBtnCancelarte(JButton btnCancelarte) {
        this.btnCancelarte = btnCancelarte;
    }

    public JButton getBtnFinalizar() {
        return btnFinalizar;
    }

    public void setBtnFinalizar(JButton btnFinalizar) {
        this.btnFinalizar = btnFinalizar;
    }

    public JButton getBtnRemovert() {
        return btnRemovert;
    }

    public void setBtnRemovert(JButton btnRemovert) {
        this.btnRemovert = btnRemovert;
    }

    public JButton getBtnSeleccionart() {
        return btnSeleccionart;
    }

    public void setBtnSeleccionart(JButton btnSeleccionart) {
        this.btnSeleccionart = btnSeleccionart;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JButton getBtnSiguientet() {
        return btnSiguientet;
    }

    public void setBtnSiguientet(JButton btnSiguientet) {
        this.btnSiguientet = btnSiguientet;
    }

    public JCheckBox getCbCasiDeler() {
        return cbCasiDeler;
    }

    public void setCbCasiDeler(JCheckBox cbCasiDeler) {
        this.cbCasiDeler = cbCasiDeler;
    }

    public JCheckBox getCbEfectDeler() {
        return cbEfectDeler;
    }

    public void setCbEfectDeler(JCheckBox cbEfectDeler) {
        this.cbEfectDeler = cbEfectDeler;
    }

    public JCheckBox getCbEfectserv() {
        return cbEfectserv;
    }

    public void setCbEfectserv(JCheckBox cbEfectserv) {
        this.cbEfectserv = cbEfectserv;
    }

    public JCheckBox getCbPropDeler() {
        return cbPropDeler;
    }

    public void setCbPropDeler(JCheckBox cbPropDeler) {
        this.cbPropDeler = cbPropDeler;
    }

    public JCheckBox getCbPropservi() {
        return cbPropservi;
    }

    public void setCbPropservi(JCheckBox cbPropservi) {
        this.cbPropservi = cbPropservi;
    }

    public JComboBox<String> getCbxClub() {
        return cbxClub;
    }

    public void setCbxClub(JComboBox<String> cbxClub) {
        this.cbxClub = cbxClub;
    }

    public JComboBox<String> getCbxOrg() {
        return cbxOrg;
    }

    public void setCbxOrg(JComboBox<String> cbxOrg) {
        this.cbxOrg = cbxOrg;
    }

    public JDialog getDlgOrganizacion() {
        return dlgOrganizacion;
    }

    public void setDlgOrganizacion(JDialog dlgOrganizacion) {
        this.dlgOrganizacion = dlgOrganizacion;
    }

    public JDialog getDlgPagos() {
        return dlgPagos;
    }

    public void setDlgPagos(JDialog dlgPagos) {
        this.dlgPagos = dlgPagos;
    }

    public JDialog getDlgTrabajadores() {
        return dlgTrabajadores;
    }

    public void setDlgTrabajadores(JDialog dlgTrabajadores) {
        this.dlgTrabajadores = dlgTrabajadores;
    }

    public JDialog getDlgeEmpleados() {
        return dlgeEmpleados;
    }

    public void setDlgeEmpleados(JDialog dlgeEmpleados) {
        this.dlgeEmpleados = dlgeEmpleados;
    }

    public JRadioButton getRbCgastos() {
        return rbCgastos;
    }

    public void setRbCgastos(JRadioButton rbCgastos) {
        this.rbCgastos = rbCgastos;
    }

    public JRadioButton getRbCgastosDeler() {
        return rbCgastosDeler;
    }

    public void setRbCgastosDeler(JRadioButton rbCgastosDeler) {
        this.rbCgastosDeler = rbCgastosDeler;
    }

    public JRadioButton getRbEfect() {
        return rbEfect;
    }

    public void setRbEfect(JRadioButton rbEfect) {
        this.rbEfect = rbEfect;
    }

    public JRadioButton getRbGastoDeler() {
        return rbGastoDeler;
    }

    public void setRbGastoDeler(JRadioButton rbGastoDeler) {
        this.rbGastoDeler = rbGastoDeler;
    }

    public JRadioButton getRbPorc() {
        return rbPorc;
    }

    public void setRbPorc(JRadioButton rbPorc) {
        this.rbPorc = rbPorc;
    }

    public JRadioButton getRbSgastos() {
        return rbSgastos;
    }

    public void setRbSgastos(JRadioButton rbSgastos) {
        this.rbSgastos = rbSgastos;
    }

    public JTextField getTxtCasiDeler() {
        return txtCasiDeler;
    }

    public void setTxtCasiDeler(JTextField txtCasiDeler) {
        this.txtCasiDeler = txtCasiDeler;
    }

    public JTextField getTxtClubEf() {
        return txtClubEf;
    }

    public void setTxtClubEf(JTextField txtClubEf) {
        this.txtClubEf = txtClubEf;
    }

    public JTextField getTxtClubPor() {
        return txtClubPor;
    }

    public void setTxtClubPor(JTextField txtClubPor) {
        this.txtClubPor = txtClubPor;
    }

    public JTextField getTxtEfectDeler() {
        return txtEfectDeler;
    }

    public void setTxtEfectDeler(JTextField txtEfectDeler) {
        this.txtEfectDeler = txtEfectDeler;
    }

    public JTextField getTxtEfectServi() {
        return txtEfectServi;
    }

    public void setTxtEfectServi(JTextField txtEfectServi) {
        this.txtEfectServi = txtEfectServi;
    }

    public JTextField getTxtPropDeler() {
        return txtPropDeler;
    }

    public void setTxtPropDeler(JTextField txtPropDeler) {
        this.txtPropDeler = txtPropDeler;
    }

    public JTextField getTxtPropServi() {
        return txtPropServi;
    }

    public void setTxtPropServi(JTextField txtPropServi) {
        this.txtPropServi = txtPropServi;
    }

    public JTextField getTxtValorAdm() {
        return txtValorAdm;
    }

    public void setTxtValorAdm(JTextField txtValorAdm) {
        this.txtValorAdm = txtValorAdm;
    }
    
      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListClub;
    private javax.swing.JList<String> ListOrg;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JTable TablaTrabajadores;
    private javax.swing.ButtonGroup bgDeler;
    private javax.swing.ButtonGroup bgGastos;
    private javax.swing.ButtonGroup bgPago;
    private javax.swing.JButton btnAceptarte;
    private javax.swing.JButton btnAgregarte;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarTr;
    private javax.swing.JButton btnCancelart;
    private javax.swing.JButton btnCancelarte;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemovert;
    private javax.swing.JButton btnSeleccionart;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnSiguientet;
    private javax.swing.JCheckBox cbCasiDeler;
    private javax.swing.JCheckBox cbEfectDeler;
    private javax.swing.JCheckBox cbEfectserv;
    private javax.swing.JCheckBox cbPropDeler;
    private javax.swing.JCheckBox cbPropservi;
    private javax.swing.JComboBox<String> cbxClub;
    private javax.swing.JComboBox<String> cbxOrg;
    private javax.swing.JDialog dlgOrganizacion;
    private javax.swing.JDialog dlgPagos;
    private javax.swing.JDialog dlgTrabajadores;
    private javax.swing.JDialog dlgeEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JRadioButton rbCgastos;
    private javax.swing.JRadioButton rbCgastosDeler;
    private javax.swing.JRadioButton rbEfect;
    private javax.swing.JRadioButton rbGastoDeler;
    private javax.swing.JRadioButton rbPorc;
    private javax.swing.JRadioButton rbSgastos;
    private javax.swing.JTextField txtCasiDeler;
    private javax.swing.JTextField txtClubEf;
    private javax.swing.JTextField txtClubPor;
    private javax.swing.JTextField txtEfectDeler;
    private javax.swing.JTextField txtEfectServi;
    private javax.swing.JTextField txtPropDeler;
    private javax.swing.JTextField txtPropServi;
    private javax.swing.JTextField txtValorAdm;
    // End of variables declaration//GEN-END:variables
}
