/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokercash.vista.principal;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTable;

/**
 *
 * @author CyberLink
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgMesa = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMesa = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        dktContenedor = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuEmpleados = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuProducto = new javax.swing.JMenuItem();
        mnuFichas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuMesa = new javax.swing.JMenuItem();
        mnuAbrirMesa = new javax.swing.JMenuItem();

        TablaMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Fecha", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaMesa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaMesa);

        btnAceptar.setText("Aceptar");

        javax.swing.GroupLayout dlgMesaLayout = new javax.swing.GroupLayout(dlgMesa.getContentPane());
        dlgMesa.getContentPane().setLayout(dlgMesaLayout);
        dlgMesaLayout.setHorizontalGroup(
            dlgMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgMesaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );
        dlgMesaLayout.setVerticalGroup(
            dlgMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgMesaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/logo_letras.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(757, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dktContenedor.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dktContenedorLayout = new javax.swing.GroupLayout(dktContenedor);
        dktContenedor.setLayout(dktContenedorLayout);
        dktContenedorLayout.setHorizontalGroup(
            dktContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dktContenedorLayout.setVerticalGroup(
            dktContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Empleados");

        mnuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/user.png"))); // NOI18N
        mnuEmpleados.setText("Ingresar Empleados");
        jMenu1.add(mnuEmpleados);

        mnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/player_new.png"))); // NOI18N
        mnuUsuario.setText("Ingresar Usuario");
        jMenu1.add(mnuUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");

        mnuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/application.png"))); // NOI18N
        mnuProducto.setText("Ingresar Producto");
        jMenu2.add(mnuProducto);

        mnuFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/chips.png"))); // NOI18N
        mnuFichas.setText("Ingresar Fichas");
        jMenu2.add(mnuFichas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mesa");

        mnuMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/table_new.png"))); // NOI18N
        mnuMesa.setText("Crear Mesa");
        jMenu3.add(mnuMesa);

        mnuAbrirMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokercash/vista/icons/tables.png"))); // NOI18N
        mnuAbrirMesa.setText("Abrir Mesa");
        jMenu3.add(mnuAbrirMesa);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dktContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dktContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getMnuMesa() {
        return mnuMesa;
    }

    public void setMnuMesa(JMenuItem mnuMesa) {
        this.mnuMesa = mnuMesa;
    }

    public JMenuItem getMnuUsuario() {
        return mnuUsuario;
    }

    public void setMnuUsaurio(JMenuItem mnuUsaurio) {
        this.mnuUsuario = mnuUsaurio;
    }

    public JDesktopPane getDktContenedor() {
        return dktContenedor;
    }

    public void setDktContenedor(JDesktopPane dktContenedor) {
        this.dktContenedor = dktContenedor;
    }

   
    public JMenuItem getMnuEmpleados() {
        return mnuEmpleados;
    }

    public void setMnuEmpleados(JMenuItem mnuEmpleados) {
        this.mnuEmpleados = mnuEmpleados;
    }

    public JMenuItem getMnuProducto() {
        return mnuProducto;
    }

    public void setMnuProducto(JMenuItem mnuProducto) {
        this.mnuProducto = mnuProducto;
    }

    public JMenuItem getMnuFichas() {
        return mnuFichas;
    }

    public void setMnuFichas(JMenuItem mnuFichas) {
        this.mnuFichas = mnuFichas;
    }

    public JDialog getDlgMesa() {
        return dlgMesa;
    }

    public void setDlgMesa(JDialog dlgMesa) {
        this.dlgMesa = dlgMesa;
    }

    public JMenuItem getMnuAbrirMesa() {
        return mnuAbrirMesa;
    }

    public void setMnuAbrirMesa(JMenuItem mnuAbrirMesa) {
        this.mnuAbrirMesa = mnuAbrirMesa;
    }

    public JTable getTablaMesa() {
        return TablaMesa;
    }

    public void setTablaMesa(JTable TablaMesa) {
        this.TablaMesa = TablaMesa;
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMesa;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JDesktopPane dktContenedor;
    private javax.swing.JDialog dlgMesa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuAbrirMesa;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenuItem mnuFichas;
    private javax.swing.JMenuItem mnuMesa;
    private javax.swing.JMenuItem mnuProducto;
    private javax.swing.JMenuItem mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
